name: Agentic Ollama DevOps AI

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  agent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          cd .github/agent
          npm ci

      - name: Run Agentic AI
        uses: ./.github/agent
        with:
          trigger_type: ${{ github.event_name }}
          comment_body: ${{ github.event.comment.body || '' }}
        env:
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
