name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: echo "hello"
    - name: Step 2
      run: echo "hello"
    - name: Step 3
      run: echo "hello"